#!/bin/bash
clear
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
ps -ef | grep "SimpleServer" | grep -v grep |awk '{print $2}' | xargs kill -9
ps -ef | grep "ARPGDemo" | grep -v grep |awk '{print $2}' | xargs kill -9

cp -rf ./Unity/Build/ARPGDemo.app ./Unity/Build/ARPGDemo2.app
open -n ./Unity/Build/ARPGDemo.app
open -n ./Unity/Build/ARPGDemo2.app

dotnet ./Server/bin/SimpleServer.dll
