
//#define DONT_USE_GENERATE_CODE                                                                 
//------------------------------------------------------------------------------                 
// <auto-generated>                                                                              
//     This code was generated by Lockstep.CodeGenerator                                         
//                                                                                               
//     Changes to this file may cause incorrect behavior and will be lost if                     
//     the code is regenerated.                                                                  
//     https://github.com/JiepengTan/LockstepPlatform                                            
// </auto-generated>                                                                             
//------------------------------------------------------------------------------                 
                                                                                                 
using Lockstep.Collision2D;                                                                  
using Lockstep.Game;                                                                  
using Lockstep.Serialization;                                                                  
public static class BackupExt {                                                                       
#if !DONT_USE_GENERATE_CODE                                                                      

       public static void WriteBackup(this Serializer writer,CAnimator data){ data.WriteBackup(writer); }    
       public static CAnimator ReadBackup(this Deserializer reader,ref CAnimator data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,CBrain data){ data.WriteBackup(writer); }    
       public static CBrain ReadBackup(this Deserializer reader,ref CBrain data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,CMover data){ data.WriteBackup(writer); }    
       public static CMover ReadBackup(this Deserializer reader,ref CMover data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,CRigidbody data){ data.WriteBackup(writer); }    
       public static CRigidbody ReadBackup(this Deserializer reader,ref CRigidbody data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,CTransform2D data){ data.WriteBackup(writer); }    
       public static CTransform2D ReadBackup(this Deserializer reader,ref CTransform2D data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,ColliderData data){ data.WriteBackup(writer); }    
       public static ColliderData ReadBackup(this Deserializer reader,ref ColliderData data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,PlayerInput data){ data.WriteBackup(writer); }    
       public static PlayerInput ReadBackup(this Deserializer reader,ref PlayerInput data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,Skill data){ data.WriteBackup(writer); }    
       public static Skill ReadBackup(this Deserializer reader,ref Skill data){data.ReadBackup(reader); return  data;}  

       public static void WriteBackup(this Serializer writer,SpawnerInfo data){ data.WriteBackup(writer); }    
       public static SpawnerInfo ReadBackup(this Deserializer reader,ref SpawnerInfo data){data.ReadBackup(reader); return  data;}                                                                         
#endif                                                                                           
}                                                                                               