
//#define DONT_USE_GENERATE_CODE                                                                 
//------------------------------------------------------------------------------                 
// <auto-generated>                                                                              
//     This code was generated by Lockstep.CodeGenerator                                         
//                                                                                               
//     Changes to this file may cause incorrect behavior and will be lost if                     
//     the code is regenerated.                                                                  
//     https://github.com/JiepengTan/LockstepPlatform                                            
// </auto-generated>                                                                             
//------------------------------------------------------------------------------                 
                                                                                                 
                                                                                                 
using Lockstep.Serialization;                                                                    
                                                                       
#if !DONT_USE_GENERATE_CODE                                                                      

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class CAnimator  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(_animLen);
			writer.Write(_curAnimIdx);
			writer.Write(_curAnimName);
			writer.Write(_timer);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			_animLen = reader.ReadLFloat();
			_curAnimIdx = reader.ReadInt32();
			_curAnimName = reader.ReadString();
			_timer = reader.ReadLFloat();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class CBrain  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(atkInterval);
			writer.Write(stopDistSqr);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			atkInterval = reader.ReadLFloat();
			stopDistSqr = reader.ReadLFloat();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class CMover  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(hasReachTarget);
			writer.Write(needMove);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			hasReachTarget = reader.ReadBoolean();
			needMove = reader.ReadBoolean();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class CRigidbody  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(Mass);
			writer.Write(Speed);
			writer.Write(isEnable);
			writer.Write(isOnFloor);
			writer.Write(isSleep);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			Mass = reader.ReadLFloat();
			Speed = reader.ReadLVector3();
			isEnable = reader.ReadBoolean();
			isOnFloor = reader.ReadBoolean();
			isSleep = reader.ReadBoolean();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Collision2D{                                                                                               
                                                                                             
    public partial class CTransform2D  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(deg);
			writer.Write(pos);
			writer.Write(y);
			writer.Write(Pos3);
			writer.Write(forward);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			deg = reader.ReadLFloat();
			pos = reader.ReadLVector2();
			y = reader.ReadLFloat();
			Pos3 = reader.ReadLVector3();
			forward = reader.ReadLVector2();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Collision2D{                                                                                               
                                                                                             
    public partial class ColliderData  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(deg);
			writer.Write(high);
			writer.Write(pos);
			writer.Write(radius);
			writer.Write(size);
			writer.Write(up);
			writer.Write(y);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			deg = reader.ReadLFloat();
			high = reader.ReadLFloat();
			pos = reader.ReadLVector2();
			radius = reader.ReadLFloat();
			size = reader.ReadLVector2();
			up = reader.ReadLVector2();
			y = reader.ReadLFloat();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class PlayerInput  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(inputUV);
			writer.Write(isInputFire);
			writer.Write(isSpeedUp);
			writer.Write(mousePos);
			writer.Write(skillId);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			inputUV = reader.ReadLVector2();
			isInputFire = reader.ReadBoolean();
			isSpeedUp = reader.ReadBoolean();
			mousePos = reader.ReadLVector2();
			skillId = reader.ReadInt32();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class Skill  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(CdTimer);
			writer.Write(_curPartIdx);
			writer.Write(skillTimer);
			writer.Write((int)(State));                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			CdTimer = reader.ReadLFloat();
			_curPartIdx = reader.ReadInt32();
			skillTimer = reader.ReadLFloat();
			State = (Lockstep.Game.Skill.ESkillState)reader.ReadInt32();                                                                                                     
        }                                         
    }                                         
 }   

 namespace Lockstep.Game{                                                                                               
                                                                                             
    public partial class SpawnerInfo  {                                                                                
        public void WriteBackup(Serializer writer){                                                          
			writer.Write(prefabId);
			writer.Write(spawnPoint);
			writer.Write(spawnTime);                                                                                                       
        }                                                                                                           
                                                                                                                    
        public void ReadBackup(Deserializer reader){                                                      
			prefabId = reader.ReadInt32();
			spawnPoint = reader.ReadLVector3();
			spawnTime = reader.ReadLFloat();                                                                                                     
        }                                         
    }                                         
 }   
                                                                              
#endif                                                                                           
                                                                                              